# Generated by Django 3.0.8 on 2020-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFirstTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.TextField(max_length=3200000)),
                ('is_activate', models.BooleanField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
