# Generated by Django 3.0.8 on 2020-09-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_advanceddatatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
